// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTwqeZ1NIiEhnMtxS_L8k1SUFUKCTAss',
    appId: '1:821505640316:web:6753c57bc764e05e3bc6f9',
    messagingSenderId: '821505640316',
    projectId: 'doolabmobile',
    authDomain: 'doolabmobile.firebaseapp.com',
    storageBucket: 'doolabmobile.appspot.com',
    measurementId: 'G-RR0RRSMMM9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYcck3m_aJllyuMvI2TNP8b9qfWdy9IU',
    appId: '1:821505640316:ios:f122c8510596af3a3bc6f9',
    messagingSenderId: '821505640316',
    projectId: 'doolabmobile',
    storageBucket: 'doolabmobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYcck3m_aJllyuMvI2TNP8b9qfWdy9IU',
    appId: '1:821505640316:ios:f122c8510596af3a3bc6f9',
    messagingSenderId: '821505640316',
    projectId: 'doolabmobile',
    storageBucket: 'doolabmobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAheCuLE93A382_8PTCOHR5fcZKFSYq8gs',
    appId: '1:821505640316:android:4172739b8f7eaf413bc6f9',
    messagingSenderId: '821505640316',
    projectId: 'doolabmobile',
    storageBucket: 'doolabmobile.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMTwqeZ1NIiEhnMtxS_L8k1SUFUKCTAss',
    appId: '1:821505640316:web:9687040f9dbe16b83bc6f9',
    messagingSenderId: '821505640316',
    projectId: 'doolabmobile',
    authDomain: 'doolabmobile.firebaseapp.com',
    storageBucket: 'doolabmobile.appspot.com',
    measurementId: 'G-6HLV0MVCG5',
  );

}